WITH selected_ucs AS (
    SELECT COLUMN_VALUE AS "UC" FROM TABLE(:UCS)
)
SELECT DISTINCT
    --UC.NUM_UC_ANEEL_UC      AS "UC_ANEEL",
    UC.ISN_UC               AS "UC",
    UC.TIPO_SIT_UC          AS "SITUACAO",
    UC.NUMERO_POSTO_UC      AS "POSTO_OPERACIONAL",
    PT.POT_INST_POSTO       AS "POT_INST_KVA",
    AG.NUM_GEDIS_ALIMG      AS "GEDIS_ALIMENTADOR",
    AL.NOME_ALIM            AS "ALIMENTADOR",
    AL.TENSAO_OPER_ALIM     AS "TENSAO_ALIMENTADOR",
    SE.NOME_SE              AS "SUBESTACAO",
    SE.SIGLA_SE             AS "SIGLA_SE",
    SE.TENSAO_NOM_SE        AS "TENSAO_SE",
    SE.CAR_SE               AS "CAR_SE",
    MU.NOME_MUN             AS "MUNICIPIO_SE",
    MU.COD_MUN              AS "COD_MUN_SE"
FROM CIS.UC_ENERGIA UC
    JOIN GDG.POSTO_TRANSFORMADOR PT
        ON UC.NUMERO_POSTO_UC = PT.NUM_OPER_POSTO
    LEFT JOIN GDG.TRECHO_PRIMARIO TR
        ON PT.NUM_GEO_TRECHO_PRIM_POSTO = TR.NUM_SEQ_GEO
    LEFT JOIN GDG.ALIMENTADOR_GEO AG
        ON TR.NUM_GEO_ALIM_TRPRIM = AG.NUM_SEQ_GEO
    LEFT JOIN SNAP_USER.ALIMENTADOR AL
        ON AL.NUM_GEDIS_ALIM = AG.NUM_GEDIS_ALIMG
        AND AG.NUM_ALIM_ALIMG = AL.NUM_SEQ_ALIM
    LEFT JOIN SNAP_USER.SUBESTACAO SE
        ON AL.NUM_SEQ_SE_ALIM = SE.NUM_SEQ_SE
    LEFT JOIN CIS.MUNICIPIO MU
    ON SE.COD_MUN_SE = MU.COD_MUN
WHERE UC.NUMERO_POSTO_UC NOT LIKE '%PTMUN'
    AND UC.TIPO_SIT_UC IN ('LG', 'CR', 'DS')
    AND AG.NUM_SEQ_GEO IN (6352460) -- Alimentador Fonte Nova
    AND EXISTS (SELECT 1 FROM selected_ucs S WHERE S."UC" = UC.ISN_UC)
